### ISSUE TITLE
How do i get this to run in eclipse?

### ISSUE THREAD

**Issue by HaginCodes** [kawakuri/2x2Optimal#1]
i imported the files into eclipse and the .iml won't open up in there so i opened in terminal. Also when i hit the "run" button, it shows a pop up "Run As" and it give me 2 options, to run it as an Ant Build and there are 2 of them and when i choose them they don't work out is says it can't find an Ant file to run. Help please?

**Comment by kclejeune** [comment]
This is an incomplete project, it won't work.

**Comment by HaginCodes** [comment]
will the project be completed?

**Comment by kclejeune** [comment]
I'd say it's unlikely, but maybe if we get some spare time in the summer.
